using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client.Message;
using Content.Shared._Stalker.PersistentCrafting;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Stalker.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftStationWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ISharedPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly TagSystem _tag;

    private static readonly Color WindowBackground = Color.FromHex("#171b22");
    private static readonly Color CardBackground = Color.FromHex("#1e222b");
    private static readonly Color CardBorder = Color.FromHex("#485060");
    private static readonly Color CardMutedBorder = Color.FromHex("#303744");
    private static readonly Color IconBackground = Color.FromHex("#11151b");
    private static readonly Color MutedText = Color.FromHex("#aab2c0");
    private static readonly Color DescriptionText = Color.FromHex("#dde2ea");
    private static readonly Color AccentWeapon = Color.FromHex("#c77532");
    private static readonly Color AccentArmor = Color.FromHex("#3d8b86");
    private static readonly Color AccentAnomaly = Color.FromHex("#77923f");
    private static readonly Color SelectedBorder = Color.FromHex("#f1d08a");
    private static readonly Color EnoughColor = Color.FromHex("#8aa06f");
    private static readonly Color MissingColor = Color.FromHex("#d46b61");

    private readonly Dictionary<PersistentCraftBranch, string> _selectedRecipes = new();
    private readonly Dictionary<PersistentCraftBranch, int> _selectedTierFilters = new();
    private readonly Dictionary<string, int> _ownedAmountCache = new();
    private bool _selectPreferredBranchOnNextUpdate = true;

    private PersistentCraftState? _state;
    private List<PersistentCraftRecipePrototype> _recipes = new();
    private string _inventorySignature = string.Empty;

    public event Action<string>? OnCraftPressed;
    public event Action? OnOpenSkillsPressed;

    public PersistentCraftStationWindow()
    {
        IoCManager.InjectDependencies(this);
        _tag = _entityManager.EntitySysManager.GetEntitySystem<TagSystem>();

        RobustXamlLoader.Load(this);

        Branches.SetTabTitle(0, Loc.GetString("persistent-craft-branch-weapon"));
        Branches.SetTabTitle(1, Loc.GetString("persistent-craft-branch-armor"));
        Branches.SetTabTitle(2, Loc.GetString("persistent-craft-branch-anomaly"));
        PointsLabel.Text = Loc.GetString("persistent-craft-window-loading-points");
        SummaryLabel.SetMarkup(Loc.GetString("persistent-craft-menu-summary-loading"));

        OpenSkillsButton.OnPressed += _ => OnOpenSkillsPressed?.Invoke();

        Branches.OnTabChanged += _ =>
        {
            if (_state == null)
                return;
            _ownedAmountCache.Clear();
            var branch = GetCurrentBranch();
            PopulateBranch(GetBranchContainer(branch), branch);
        };
    }

    public void UpdateState(PersistentCraftState state, IEnumerable<PersistentCraftRecipePrototype> recipes)
    {
        _state = state;
        _recipes = recipes
            .OrderBy(recipe => recipe.Branch)
            .ThenBy(recipe => recipe.Tier)
            .ThenBy(recipe => recipe.SubTier)
            .ThenBy(recipe => recipe.ID)
            .ToList();
        _ownedAmountCache.Clear();
        _inventorySignature = BuildInventorySignature();

        if (state.Loaded && _selectPreferredBranchOnNextUpdate)
        {
            SelectPreferredBranchTab();
            _selectPreferredBranchOnNextUpdate = false;
        }

        Render();
    }

    public void ResetInitialTabSelection()
    {
        _selectPreferredBranchOnNextUpdate = true;
    }

    public void RefreshLocalInventory()
    {
        if (_state == null)
            return;

        var newSignature = BuildInventorySignature();
        if (newSignature == _inventorySignature)
            return;

        _inventorySignature = newSignature;
        _ownedAmountCache.Clear();

        // Rebuild only the currently visible branch to avoid flickering
        var branch = GetCurrentBranch();
        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private void Render()
    {
        if (_state == null)
            return;

        if (!_state.Loaded)
        {
            PointsLabel.Text = Loc.GetString("persistent-craft-window-loading-points");
            SummaryLabel.SetMarkup(Loc.GetString("persistent-craft-menu-summary-loading"));
        }
        else
        {
            PointsLabel.Text = Loc.GetString("persistent-craft-points", ("points", BuildPointsSummary(_state)));
            SummaryLabel.SetMarkup(BuildSummaryMarkup(_state));
        }

        var branch = GetCurrentBranch();
        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private void PopulateBranch(BoxContainer container, PersistentCraftBranch branch)
    {
        container.RemoveAllChildren();

        if (_state == null)
            return;

        var branchRecipes = _recipes
            .Where(recipe => recipe.Branch == branch)
            .ToList();

        if (branchRecipes.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-none"),
                FontColorOverride = MutedText,
            });
            return;
        }

        var branchState = GetBranchState(_state, branch);
        var unlockedRecipes = _state.Loaded
            ? branchRecipes.Where(recipe => HasRequirement(_state, recipe)).ToList()
            : new List<PersistentCraftRecipePrototype>();

        container.AddChild(CreateBranchHeader(branch, branchState, unlockedRecipes.Count, branchRecipes.Count));
        container.AddChild(new Control { MinSize = new Vector2(1, 12) });

        if (!_state.Loaded)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-window-loading-points"),
                FontColorOverride = MutedText,
            });
            return;
        }

        if (branchRecipes.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-station-no-recipes"),
                FontColorOverride = MutedText,
            });
            return;
        }

        if (unlockedRecipes.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-station-no-recipes"),
                FontColorOverride = MutedText,
            });
            return;
        }

        var selectedTier = GetSelectedTierFilter(branch, unlockedRecipes, branchState);
        container.AddChild(CreateTierFilterRow(branch, unlockedRecipes, selectedTier, GetAccent(branch)));
        container.AddChild(new Control { MinSize = new Vector2(1, 12) });

        var filteredRecipes = selectedTier > 0
            ? unlockedRecipes.Where(recipe => recipe.Tier == selectedTier).ToList()
            : unlockedRecipes;

        var selected = ResolveSelectedRecipe(branch, filteredRecipes);

        var contentRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalExpand = true,
            MinSize = new Vector2(0, 500),
            SeparationOverride = 12,
        };

        var listScroll = new ScrollContainer
        {
            MinSize = new Vector2(360, 500),
            VerticalExpand = true,
            HScrollEnabled = false,
        };
        listScroll.AddChild(CreateRecipeList(filteredRecipes, selected, GetAccent(branch)));
        contentRow.AddChild(listScroll);

        var detailScroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            MinSize = new Vector2(0, 500),
            HScrollEnabled = false,
        };
        detailScroll.AddChild(CreateRecipeDetailsPanel(selected, branchState));
        contentRow.AddChild(detailScroll);

        container.AddChild(contentRow);
    }

    private BoxContainer CreateTierFilterRow(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftRecipePrototype> recipes,
        int selectedTier,
        Color accent)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        row.AddChild(CreateTierFilterButton(branch, 0, Loc.GetString("persistent-craft-filter-all"), selectedTier == 0, accent));

        foreach (var tier in recipes.Select(recipe => recipe.Tier).Distinct().OrderBy(tier => tier))
        {
            row.AddChild(new Control { MinSize = new Vector2(6, 1) });
            row.AddChild(CreateTierFilterButton(
                branch,
                tier,
                PersistentCraftingHelper.GetTierDisplayLabel(tier),
                selectedTier == tier,
                accent));
        }

        return row;
    }

    private Button CreateTierFilterButton(
        PersistentCraftBranch branch,
        int tier,
        string text,
        bool selected,
        Color accent)
    {
        var button = new Button
        {
            Text = text,
            MinSize = new Vector2(42, 28),
            ModulateSelfOverride = selected ? Color.White : Color.White.WithAlpha(0.85f),
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = selected ? accent.WithAlpha(0.18f) : CardBackground,
                BorderColor = selected ? accent : CardMutedBorder,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            }
        };

        button.OnPressed += _ => SelectTierFilter(branch, tier);
        return button;
    }

    private PanelContainer CreateBranchHeader(
        PersistentCraftBranch branch,
        PersistentCraftBranchState branchState,
        int unlockedRecipes,
        int totalRecipes)
    {
        var accent = GetAccent(branch);
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CardBackground,
                BorderColor = accent,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8,
            }
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        row.AddChild(new Label
        {
            Text = Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(branch)),
            FontColorOverride = accent,
        });
        row.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-level-label")}: {PersistentCraftingHelper.FormatLevel(branchState.Level, branchState.SubLevel)} | " +
                   $"{Loc.GetString("persistent-craft-branch-points-label")}: {branchState.AvailablePoints} | " +
                   $"{Loc.GetString("persistent-craft-recipes-short")}: {unlockedRecipes}/{totalRecipes}",
            FontColorOverride = Color.White,
            ClipText = true,
        });

        body.AddChild(row);
        body.AddChild(new Control { MinSize = new Vector2(1, 5) });

        var xpProgress = branchState.ExperienceForNextLevel > 0
            ? Math.Clamp((float)branchState.Experience / branchState.ExperienceForNextLevel, 0f, 1f)
            : 0f;
        body.AddChild(new ProgressBar
        {
            MinSize = new Vector2(0, 6),
            HorizontalExpand = true,
            Value = xpProgress,
        });
        body.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-experience-label")}: {branchState.Experience} / {branchState.ExperienceForNextLevel}",
            FontColorOverride = MutedText,
        });

        panel.AddChild(body);
        return panel;
    }

    private BoxContainer CreateRecipeList(
        IReadOnlyList<PersistentCraftRecipePrototype> recipes,
        PersistentCraftRecipePrototype selected,
        Color accent)
    {
        var list = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        foreach (var tierGroup in recipes.GroupBy(recipe => recipe.Tier).OrderBy(group => group.Key))
        {
            list.AddChild(CreateTierHeader(tierGroup.Key, accent));
            list.AddChild(new Control { MinSize = new Vector2(1, 6) });

            foreach (var categoryGroup in tierGroup
                         .GroupBy(GetRecipeCategoryId)
                         .OrderBy(group => GetCategoryOrder(group.Key)))
            {
                list.AddChild(CreateCategoryHeader(GetCategoryName(categoryGroup.Key), accent));
                list.AddChild(new Control { MinSize = new Vector2(1, 4) });

                foreach (var subCategoryGroup in categoryGroup
                             .GroupBy(GetRecipeSubCategoryId)
                             .OrderBy(group => GetSubCategoryOrder(group.Key)))
                {
                    var subCategoryId = subCategoryGroup.Key;
                    if (!string.IsNullOrWhiteSpace(subCategoryId))
                    {
                        list.AddChild(CreateSubCategoryHeader(GetSubCategoryName(subCategoryId)));
                        list.AddChild(new Control { MinSize = new Vector2(1, 4) });
                    }

                    foreach (var recipe in subCategoryGroup.OrderBy(item => item.Tier).ThenBy(item => item.SubTier).ThenBy(item => item.ID))
                    {
                        list.AddChild(CreateRecipeListEntry(recipe, selected.ID == recipe.ID));
                    }
                }
            }
        }

        return list;
    }

    private Control CreateTierHeader(int tier, Color accent)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 6),
        };

        var strip = new PanelContainer
        {
            MinSize = new Vector2(3, 0),
            PanelOverride = new StyleBoxFlat { BackgroundColor = accent },
        };

        var label = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = WindowBackground,
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 5,
                ContentMarginBottomOverride = 5,
            }
        };
        label.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-level-label")} {PersistentCraftingHelper.GetTierDisplayLabel(tier)}",
            FontColorOverride = accent,
        });

        row.AddChild(strip);
        row.AddChild(label);
        return row;
    }

    private Control CreateCategoryHeader(string text, Color accent)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 6),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CardBackground,
                BorderColor = CardMutedBorder,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 5,
                ContentMarginBottomOverride = 5,
            }
        };

        panel.AddChild(new Label
        {
            Text = text,
            FontColorOverride = accent,
        });

        return panel;
    }

    private Control CreateSubCategoryHeader(string text)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = MutedText,
        };
    }

    private ContainerButton CreateRecipeListEntry(PersistentCraftRecipePrototype recipe, bool selected)
    {
        var loaded = _state?.Loaded == true;
        var requirementMet = _state != null && HasRequirement(_state, recipe);
        var hasMaterials = HasLocalMaterials(recipe);
        var canCraft = loaded && requirementMet && hasMaterials;
        var accent = GetAccent(recipe.Branch);
        var background = requirementMet ? CardBackground : WindowBackground;
        var border = selected ? SelectedBorder : requirementMet ? accent : CardBorder;

        var button = new ContainerButton
        {
            HorizontalExpand = true,
            MinSize = new Vector2(0, 78),
            Margin = new Thickness(0, 0, 0, 8),
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = background,
                BorderColor = border,
                BorderThickness = new Thickness(selected ? 2 : 1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 10,
                ContentMarginBottomOverride = 10,
            }
        };

        button.OnPressed += _ => SelectRecipe(recipe.Branch, recipe.ID);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        row.AddChild(CreateRecipeIcon(recipe, selected ? SelectedBorder : accent, new Vector2(48, 48)));
        row.AddChild(new Control { MinSize = new Vector2(10, 1) });

        var textColumn = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        textColumn.AddChild(new Label
        {
            Text = ResolveRecipeName(recipe),
            FontColorOverride = requirementMet ? Color.White : MutedText,
            ClipText = true,
        });

        textColumn.AddChild(new Label
        {
            Text = BuildRecipeMetaLine(recipe, loaded, requirementMet, hasMaterials),
            FontColorOverride = !requirementMet ? MissingColor : canCraft ? accent : hasMaterials ? MutedText : MissingColor,
            ClipText = true,
        });

        row.AddChild(textColumn);
        button.AddChild(row);

        return button;
    }

    private PanelContainer CreateRecipeDetailsPanel(
        PersistentCraftRecipePrototype recipe,
        PersistentCraftBranchState branchState)
    {
        var loaded = _state?.Loaded == true;
        var requirementMet = _state != null && HasRequirement(_state, recipe);
        var hasMaterials = HasLocalMaterials(recipe);
        var canCraft = loaded && requirementMet && hasMaterials;
        var accent = GetAccent(recipe.Branch);

        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = WindowBackground,
                BorderColor = accent,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 14,
                ContentMarginRightOverride = 14,
                ContentMarginTopOverride = 14,
                ContentMarginBottomOverride = 14,
            }
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        var topRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var leftColumn = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            MinSize = new Vector2(108, 0),
        };
        leftColumn.AddChild(CreateRecipeIcon(recipe, accent, new Vector2(96, 96)));
        leftColumn.AddChild(new Control { MinSize = new Vector2(1, 10) });

        var craftButton = new Button
        {
            Text = Loc.GetString("persistent-craft-recipe-action"),
            Disabled = !canCraft,
            HorizontalExpand = true,
            MinSize = new Vector2(0, 34),
        };
        craftButton.OnPressed += _ => OnCraftPressed?.Invoke(recipe.ID);
        leftColumn.AddChild(craftButton);

        topRow.AddChild(leftColumn);
        topRow.AddChild(new Control { MinSize = new Vector2(14, 1) });

        var titleColumn = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        titleColumn.AddChild(new Label
        {
            Text = ResolveRecipeName(recipe),
            FontColorOverride = Color.White,
            ClipText = true,
        });
        titleColumn.AddChild(new Control { MinSize = new Vector2(1, 6) });
        titleColumn.AddChild(CreateMetaBadge(
            $"{Loc.GetString("persistent-craft-level-label")}: {PersistentCraftingHelper.FormatLevel(branchState.Level, branchState.SubLevel)}",
            IconBackground,
            Color.White));
        titleColumn.AddChild(new Control { MinSize = new Vector2(1, 6) });
        titleColumn.AddChild(CreateMetaBadge(
            $"{Loc.GetString("persistent-craft-level-label")} {PersistentCraftingHelper.GetTierDisplayLabel(recipe.Tier)} | {PersistentCraftingHelper.GetRecipeLevelText(recipe)}",
            IconBackground,
            accent));
        titleColumn.AddChild(new Control { MinSize = new Vector2(1, 6) });
        titleColumn.AddChild(CreateMetaBadge(
            $"{Loc.GetString("persistent-craft-recipe-experience")}: +{PersistentCraftingHelper.GetExperienceReward(recipe)}",
            IconBackground,
            Color.White));
        titleColumn.AddChild(new Control { MinSize = new Vector2(1, 6) });
        titleColumn.AddChild(CreateMetaBadge(
            BuildRecipeMasteryBadge(recipe),
            IconBackground,
            requirementMet ? accent : MutedText));
        titleColumn.AddChild(new Control { MinSize = new Vector2(1, 6) });
        titleColumn.AddChild(CreateMetaBadge(
            GetRecipeCategoryPath(recipe),
            IconBackground,
            MutedText));

        topRow.AddChild(titleColumn);
        body.AddChild(topRow);
        body.AddChild(new Control { MinSize = new Vector2(1, 12) });

        body.AddChild(CreateSection(
            $"[color={DescriptionText.ToHex()}]{FormattedMessage.EscapeText(ResolveRecipeDescription(recipe))}[/color]",
            6));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });

        body.AddChild(CreateSection(
            $"[color={MutedText.ToHex()}]{Loc.GetString("persistent-craft-recipe-requirement")}:[/color]\n{BuildRequirementMarkup(recipe)}",
            5));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });

        body.AddChild(CreateSection(
            $"[color={MutedText.ToHex()}]{Loc.GetString("persistent-craft-recipe-ingredients")}:[/color]\n{BuildIngredientMarkup(recipe)}",
            5));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });

        body.AddChild(CreateSection(
            $"[color={MutedText.ToHex()}]{Loc.GetString("persistent-craft-recipe-results")}:[/color]\n{BuildResultMarkup(recipe)}",
            5));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });

        body.AddChild(CreateSection(
            $"[color={MutedText.ToHex()}]{Loc.GetString("persistent-craft-recipe-time")}: {GetEffectiveCraftTime(recipe):0.#} {Loc.GetString("persistent-craft-recipe-seconds")}\n" +
            $"{Loc.GetString("persistent-craft-recipe-status")}: {Loc.GetString(GetStatusKey(loaded, requirementMet, hasMaterials))}[/color]",
            5));
        body.AddChild(new Control { VerticalExpand = true });
        panel.AddChild(body);

        return panel;
    }

    private PanelContainer CreateSection(string markupText, int padding)
    {
        var section = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CardBackground,
                BorderColor = CardMutedBorder,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = padding,
                ContentMarginRightOverride = padding,
                ContentMarginTopOverride = padding,
                ContentMarginBottomOverride = padding,
            }
        };

        var label = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        label.SetMarkup(markupText);
        section.AddChild(label);

        return section;
    }

    private PanelContainer CreateRecipeIcon(PersistentCraftRecipePrototype recipe, Color accent, Vector2 size)
    {
        var panel = new PanelContainer
        {
            MinSize = size,
            RectClipContent = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = IconBackground,
                BorderColor = accent,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
            },
        };

        if (TryGetRecipeTexture(recipe, out var texture))
        {
            panel.AddChild(new TextureRect
            {
                Texture = texture,
                TextureScale = size.X >= 90 ? new Vector2(2.1f, 2.1f) : new Vector2(1.15f, 1.15f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            });
        }
        else
        {
            panel.AddChild(new Label
            {
                Text = PersistentCraftingHelper.GetRecipeLevelText(recipe),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            });
        }

        return panel;
    }

    private PanelContainer CreateMetaBadge(string text, Color background, Color foreground)
    {
        var badge = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = background,
                BorderColor = background,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 7,
                ContentMarginRightOverride = 7,
                ContentMarginTopOverride = 3,
                ContentMarginBottomOverride = 3,
            }
        };

        badge.AddChild(new Label
        {
            Text = text,
            FontColorOverride = foreground,
            ClipText = true,
        });

        return badge;
    }

    private void SelectRecipe(PersistentCraftBranch branch, string recipeId)
    {
        _selectedRecipes[branch] = recipeId;
        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private void SelectTierFilter(PersistentCraftBranch branch, int tier)
    {
        _selectedTierFilters[branch] = tier;
        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private BoxContainer GetBranchContainer(PersistentCraftBranch branch) => branch switch
    {
        PersistentCraftBranch.Armor => ArmorBranch,
        PersistentCraftBranch.Anomaly => AnomalyBranch,
        _ => WeaponBranch,
    };

    private PersistentCraftBranch GetCurrentBranch() => Branches.CurrentTab switch
    {
        1 => PersistentCraftBranch.Armor,
        2 => PersistentCraftBranch.Anomaly,
        _ => PersistentCraftBranch.Weapon,
    };

    private PersistentCraftRecipePrototype ResolveSelectedRecipe(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftRecipePrototype> recipes)
    {
        if (_selectedRecipes.TryGetValue(branch, out var selectedId))
        {
            var existing = recipes.FirstOrDefault(recipe => recipe.ID == selectedId);
            if (existing != null)
                return existing;
        }

        var fallback = _state == null
            ? recipes[0]
            : recipes.FirstOrDefault(recipe => HasRequirement(_state, recipe)) ?? recipes[0];

        _selectedRecipes[branch] = fallback.ID;
        return fallback;
    }

    private int GetSelectedTierFilter(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftRecipePrototype> recipes,
        PersistentCraftBranchState branchState)
    {
        if (_selectedTierFilters.TryGetValue(branch, out var selectedTier) &&
            (selectedTier == 0 || recipes.Any(recipe => recipe.Tier == selectedTier)))
        {
            return selectedTier;
        }

        var preferredTier = 0;
        if (_state?.Loaded == true)
        {
            preferredTier = recipes
                .Where(recipe => HasRequirement(_state, recipe))
                .Select(recipe => recipe.Tier)
                .DefaultIfEmpty(Math.Min(branchState.Level, recipes.Max(recipe => recipe.Tier)))
                .Max();
        }

        _selectedTierFilters[branch] = preferredTier;
        return preferredTier;
    }

    private bool TryGetRecipeTexture(PersistentCraftRecipePrototype recipe, out Texture? texture)
    {
        texture = null;
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (string.IsNullOrWhiteSpace(displayProto))
            return false;

        try
        {
            var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
            texture = spriteSystem.GetPrototypeIcon(displayProto).Default;
            return texture != null;
        }
        catch
        {
            texture = null;
            return false;
        }
    }

    private bool HasRequirement(PersistentCraftState state, PersistentCraftRecipePrototype recipe)
    {
        var requiredNode = string.IsNullOrWhiteSpace(recipe.RequiredNode)
            ? PersistentCraftingHelper.BuildNodeId(recipe.Branch, recipe.Tier, recipe.SubTier)
            : recipe.RequiredNode;

        return !string.IsNullOrWhiteSpace(requiredNode) && HasNodeUnlockedOrAutoAvailable(state, requiredNode);
    }

    private string GetRequirementText(PersistentCraftRecipePrototype recipe)
    {
        if (TryResolveRequirementNode(recipe, out var node))
        {
            return $"{ResolveNodeName(node)} [{PersistentCraftingHelper.GetNodeLevelText(node)}]";
        }

        return $"{Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(recipe.Branch))} {PersistentCraftingHelper.GetRecipeLevelText(recipe)}";
    }

    private string GetRequirementBadgeText(PersistentCraftRecipePrototype recipe)
    {
        if (TryResolveRequirementNode(recipe, out var node))
            return PersistentCraftingHelper.GetNodeLevelText(node);

        return PersistentCraftingHelper.GetRecipeLevelText(recipe);
    }

    private string BuildRecipeMetaLine(
        PersistentCraftRecipePrototype recipe,
        bool loaded,
        bool requirementMet,
        bool hasMaterials)
    {
        var status = Loc.GetString(GetStatusKey(loaded, requirementMet, hasMaterials));
        return $"{PersistentCraftingHelper.GetRecipeLevelText(recipe)} | {status}";
    }

    private string BuildRecipeMasteryBadge(PersistentCraftRecipePrototype recipe)
    {
        if (!TryResolveRequirementNode(recipe, out var node))
            return Loc.GetString("persistent-craft-node-mastery-short", ("level", PersistentCraftingHelper.InitialNodeMasteryLevel), ("max", PersistentCraftingHelper.MaxNodeMasteryLevel));

        return BuildNodeMasteryText(node);
    }

    private string BuildRequirementMarkup(PersistentCraftRecipePrototype recipe)
    {
        if (TryResolveRequirementNode(recipe, out var node))
        {
            var mastery = BuildNodeMasteryText(node);
            return $"[color={DescriptionText.ToHex()}]- {FormattedMessage.EscapeText(ResolveNodeName(node))} ({FormattedMessage.EscapeText(PersistentCraftingHelper.GetNodeLevelText(node))})[/color]\n" +
                   $"[color={MutedText.ToHex()}]- {FormattedMessage.EscapeText(mastery)}[/color]";
        }

        return $"[color={DescriptionText.ToHex()}]- {FormattedMessage.EscapeText(GetRequirementText(recipe))}[/color]";
    }

    private string BuildNodeMasteryText(PersistentCraftNodePrototype node)
    {
        var nodeState = GetNodeState(node);
        if (nodeState == null)
        {
            return Loc.GetString(
                "persistent-craft-node-mastery-short",
                ("level", PersistentCraftingHelper.InitialNodeMasteryLevel),
                ("max", PersistentCraftingHelper.MaxNodeMasteryLevel));
        }

        if (nodeState.ExperienceForNextLevel <= 0)
        {
            return Loc.GetString(
                "persistent-craft-node-mastery-max",
                ("level", nodeState.MasteryLevel),
                ("max", PersistentCraftingHelper.MaxNodeMasteryLevel));
        }

        return Loc.GetString(
            "persistent-craft-node-mastery-progress",
            ("level", nodeState.MasteryLevel),
            ("max", PersistentCraftingHelper.MaxNodeMasteryLevel),
            ("experience", nodeState.Experience),
            ("next", nodeState.ExperienceForNextLevel));
    }

    private bool TryResolveRequirementNode(PersistentCraftRecipePrototype recipe, out PersistentCraftNodePrototype node)
    {
        var requiredNode = string.IsNullOrWhiteSpace(recipe.RequiredNode)
            ? PersistentCraftingHelper.BuildNodeId(recipe.Branch, recipe.Tier, recipe.SubTier)
            : recipe.RequiredNode;

        PersistentCraftNodePrototype? resolvedNode;
        if (!string.IsNullOrWhiteSpace(requiredNode) &&
            _prototype.TryIndex<PersistentCraftNodePrototype>(requiredNode, out resolvedNode) &&
            resolvedNode != null)
        {
            node = resolvedNode;
            return true;
        }

        node = default!;
        return false;
    }

    private void SelectPreferredBranchTab()
    {
        if (_state == null)
            return;

        var preferred = PersistentCraftingHelper.EnumerateBranches()
            .Select(branch => new
            {
                Branch = branch,
                Recipes = _recipes.Count(recipe => recipe.Branch == branch && HasRequirement(_state, recipe)),
                Points = GetBranchState(_state, branch).AvailablePoints,
            })
            .OrderByDescending(entry => entry.Recipes)
            .ThenByDescending(entry => entry.Points)
            .FirstOrDefault(entry => entry.Recipes > 0 || entry.Points > 0);

        if (preferred != null)
            Branches.CurrentTab = GetBranchTabIndex(preferred.Branch);
    }

    private static int GetBranchTabIndex(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => 0,
            PersistentCraftBranch.Armor => 1,
            PersistentCraftBranch.Anomaly => 2,
            _ => 0,
        };
    }

    private string GetRecipeCategoryId(PersistentCraftRecipePrototype recipe)
    {
        if (!string.IsNullOrWhiteSpace(recipe.Category))
            return recipe.Category!;

        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe) ?? string.Empty;

        return recipe.Branch switch
        {
            PersistentCraftBranch.Weapon when displayProto.Contains("Mag") => "magazines",
            PersistentCraftBranch.Weapon when displayProto.Contains("Box") => "ammo",
            PersistentCraftBranch.Weapon => "weapons",

            PersistentCraftBranch.Armor when displayProto.StartsWith("Medkit") => "medicine",
            PersistentCraftBranch.Armor when displayProto.StartsWith("ClothingBackpack") => "bags",
            PersistentCraftBranch.Armor when displayProto.StartsWith("ClothingHeadHelmet") || displayProto.StartsWith("ClothingMask") => "headgear",
            PersistentCraftBranch.Armor => "armor",

            PersistentCraftBranch.Anomaly when displayProto.Contains("ArtifactContainer") => "containers",
            PersistentCraftBranch.Anomaly when displayProto.StartsWith("ZoneAnomalyDetector") => "anomaly-detectors",
            PersistentCraftBranch.Anomaly when displayProto.StartsWith("ZoneArtifactDetector") => "artifact-detectors",
            _ => "special",
        };
    }

    private string GetRecipeSubCategoryId(PersistentCraftRecipePrototype recipe)
    {
        if (!string.IsNullOrWhiteSpace(recipe.SubCategory))
            return recipe.SubCategory!;

        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe) ?? string.Empty;
        var category = GetRecipeCategoryId(recipe);

        if (recipe.Branch == PersistentCraftBranch.Weapon)
        {
            if (displayProto.Contains("545") || displayProto.Contains("AKS74") || displayProto.Contains("AK74") || displayProto.Contains("A545") || displayProto.Contains("AK12") || displayProto.Contains("RPK16"))
                return "caliber-545";

            if (displayProto.Contains("556") || displayProto.Contains("M16") || displayProto.Contains("M4") || displayProto.Contains("G36") || displayProto.Contains("HK416") || displayProto.Contains("SCARL") || displayProto.Contains("F2000"))
                return "caliber-556";
        }

        if (recipe.Branch == PersistentCraftBranch.Armor)
        {
            if (category == "headgear")
                return displayProto.StartsWith("ClothingMask") ? "masks" : "helmets";

            if (category == "bags")
                return "backpacks";

            if (category == "medicine")
                return "medkits";
        }

        if (recipe.Branch == PersistentCraftBranch.Anomaly)
        {
            return category switch
            {
                "anomaly-detectors" => "scanner-line",
                "artifact-detectors" => "artifact-line",
                "containers" => "containers-line",
                _ => $"tier-{recipe.Tier}",
            };
        }

        return string.Empty;
    }

    private string GetCategoryName(string categoryId)
    {
        var locKey = $"persistent-craft-category-{categoryId}";
        return TryLoc(locKey) ?? categoryId;
    }

    private string GetSubCategoryName(string subCategoryId)
    {
        if (string.IsNullOrWhiteSpace(subCategoryId))
            return string.Empty;

        if (subCategoryId.StartsWith("tier-") && int.TryParse(subCategoryId["tier-".Length..], out var tier))
            return $"{Loc.GetString("persistent-craft-level-label")} {PersistentCraftingHelper.GetTierDisplayLabel(tier)}";

        var locKey = $"persistent-craft-subcategory-{subCategoryId}";
        return TryLoc(locKey) ?? subCategoryId;
    }

    private static int GetCategoryOrder(string categoryId)
    {
        return categoryId switch
        {
            "ammo" => 0,
            "magazines" => 1,
            "weapons" => 2,
            "armor" => 0,
            "headgear" => 1,
            "bags" => 2,
            "medicine" => 3,
            "anomaly-detectors" => 0,
            "artifact-detectors" => 1,
            "containers" => 2,
            _ => 99,
        };
    }

    private static int GetSubCategoryOrder(string subCategoryId)
    {
        return subCategoryId switch
        {
            "caliber-545" => 0,
            "caliber-556" => 1,
            "helmets" => 0,
            "masks" => 1,
            "backpacks" => 0,
            "medkits" => 1,
            "scanner-line" => 0,
            "artifact-line" => 1,
            "containers-line" => 2,
            _ => 99,
        };
    }

    private static string? TryLoc(string locKey)
    {
        try
        {
            return Loc.GetString(locKey);
        }
        catch
        {
            return null;
        }
    }

    private string GetRecipeCategoryPath(PersistentCraftRecipePrototype recipe)
    {
        var category = GetCategoryName(GetRecipeCategoryId(recipe));
        var subCategory = GetSubCategoryName(GetRecipeSubCategoryId(recipe));

        return string.IsNullOrWhiteSpace(subCategory)
            ? category
            : $"{category} / {subCategory}";
    }

    private bool HasNodeUnlockedOrAutoAvailable(PersistentCraftState state, string nodeId)
    {
        return HasNodeUnlockedOrAutoAvailable(state, nodeId, new HashSet<string>());
    }

    private bool HasNodeUnlockedOrAutoAvailable(PersistentCraftState state, string nodeId, HashSet<string> path)
    {
        if (state.UnlockedNodes.Contains(nodeId))
            return true;

        if (!_prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var node))
            return false;

        if (node.Cost > 0)
            return false;

        var branchState = GetBranchState(state, node.Branch);
        if (branchState.Level < PersistentCraftingHelper.GetNodeRequiredBranchLevel(node))
            return false;

        if (!path.Add(nodeId))
            return false;

        try
        {
            return node.Prerequisites.All(prerequisite => HasNodeUnlockedOrAutoAvailable(state, prerequisite, path));
        }
        finally
        {
            path.Remove(nodeId);
        }
    }

    private string BuildIngredientMarkup(PersistentCraftRecipePrototype recipe)
    {
        return string.Join("\n", recipe.Ingredients.Select(ingredient => FormatIngredientLine(recipe, ingredient)));
    }

    private string BuildResultMarkup(PersistentCraftRecipePrototype recipe)
    {
        return string.Join("\n", recipe.Results.Select(result =>
            $"[color={DescriptionText.ToHex()}]- {FormattedMessage.EscapeText(FormatResult(result))}[/color]"));
    }

    private string FormatIngredient(PersistentCraftIngredient ingredient)
    {
        var name = !string.IsNullOrWhiteSpace(ingredient.Proto)
            ? ResolveEntityName(ingredient.Proto)
            : $"#{ingredient.Tag}";

        return $"{name} x{ingredient.Amount}";
    }

    private string FormatResult(PersistentCraftResult result)
    {
        return $"{ResolveEntityName(result.Proto)} x{result.Amount}";
    }

    private string FormatIngredientLine(PersistentCraftRecipePrototype recipe, PersistentCraftIngredient ingredient)
    {
        var requiredAmount = GetEffectiveIngredientAmount(recipe, ingredient);
        var owned = GetOwnedAmount(ingredient);
        var enough = owned >= requiredAmount;
        var color = enough ? EnoughColor : MissingColor;
        return $"[color={color.ToHex()}]- {FormattedMessage.EscapeText(FormatIngredient(ingredient))} ({owned}/{requiredAmount})[/color]";
    }

    private bool HasLocalMaterials(PersistentCraftRecipePrototype recipe)
    {
        return recipe.Ingredients.All(ingredient => GetOwnedAmount(ingredient) >= GetEffectiveIngredientAmount(recipe, ingredient));
    }

    private int GetOwnedAmount(PersistentCraftIngredient ingredient)
    {
        var cacheKey = GetIngredientCacheKey(ingredient);
        if (_ownedAmountCache.TryGetValue(cacheKey, out var cached))
            return cached;

        if (_player.LocalEntity is not { Valid: true } user || !_entityManager.EntityExists(user))
            return 0;

        var amount = PersistentCraftInventoryHelper.CountIngredientAmount(
            _entityManager,
            _prototype,
            _tag,
            user,
            ingredient);
        _ownedAmountCache[cacheKey] = amount;
        return amount;
    }

    private string ResolveEntityName(string prototypeId)
    {
        return _prototype.TryIndex<EntityPrototype>(prototypeId, out var prototype)
            ? prototype.Name
            : prototypeId;
    }

    private string ResolveRecipeName(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype))
        {
            return prototype.Name;
        }

        return Loc.GetString(recipe.Name);
    }

    private string ResolveRecipeDescription(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype) &&
            !string.IsNullOrWhiteSpace(prototype.Description))
        {
            return prototype.Description;
        }

        return Loc.GetString(recipe.Description);
    }

    private string ResolveNodeName(PersistentCraftNodePrototype node)
    {
        return string.IsNullOrWhiteSpace(node.Name)
            ? PersistentCraftingHelper.GetNodeLevelText(node)
            : Loc.GetString(node.Name);
    }

    private string BuildPointsSummary(PersistentCraftState state)
    {
        return string.Join(" | ", PersistentCraftingHelper.EnumerateBranches().Select(branch =>
        {
            var branchState = GetBranchState(state, branch);
            return $"{Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(branch))}: {branchState.AvailablePoints}";
        }));
    }

    private string BuildSummaryMarkup(PersistentCraftState state)
    {
        var lines = PersistentCraftingHelper.EnumerateBranches().Select(branch =>
        {
            var branchState = GetBranchState(state, branch);
            return $"[color={MutedText.ToHex()}]{Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(branch))}: " +
                   $"{PersistentCraftingHelper.FormatLevel(branchState.Level, branchState.SubLevel)} | " +
                   $"{Loc.GetString("persistent-craft-experience-label")}: {branchState.Experience}/{branchState.ExperienceForNextLevel} | " +
                   $"{Loc.GetString("persistent-craft-points-short")}: {branchState.AvailablePoints}[/color]";
        }).ToList();

        lines.Add($"[color={MutedText.ToHex()}]{Loc.GetString("persistent-craft-unlocked-summary", ("unlocked", state.UnlockedNodes.Count))}. {Loc.GetString("persistent-craft-menu-material-note")}[/color]");
        return string.Join("\n", lines);
    }

    private static PersistentCraftBranchState GetBranchState(PersistentCraftState state, PersistentCraftBranch branch)
    {
        return state.BranchStates.FirstOrDefault(item => item.Branch == branch) ??
               new PersistentCraftBranchState(
                   branch,
                   0,
                   0,
                   PersistentCraftingHelper.InitialLevel,
                   PersistentCraftingHelper.MainTierSubLevel,
                   0,
                   PersistentCraftingHelper.GetExperienceForNextLevel(PersistentCraftingHelper.InitialLevel));
    }

    private PersistentCraftNodeState? GetNodeState(PersistentCraftNodePrototype node)
    {
        return _state?.NodeStates.FirstOrDefault(item => item.NodeId == node.ID);
    }

    private static string GetStatusKey(bool loaded, bool requirementMet, bool hasMaterials)
    {
        if (!loaded)
            return "persistent-craft-station-status-loading";

        if (!requirementMet)
            return "persistent-craft-station-status-locked";

        return hasMaterials
            ? "persistent-craft-station-status-available"
            : "persistent-craft-station-status-missing-materials";
    }

    private static Color GetAccent(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => AccentWeapon,
            PersistentCraftBranch.Armor => AccentArmor,
            PersistentCraftBranch.Anomaly => AccentAnomaly,
            _ => CardBorder,
        };
    }

    private static string GetIngredientCacheKey(PersistentCraftIngredient ingredient)
    {
        return $"{ingredient.Proto ?? string.Empty}|{ingredient.Tag ?? string.Empty}";
    }

    private string BuildInventorySignature()
    {
        if (_player.LocalEntity is not { Valid: true } user || !_entityManager.EntityExists(user))
            return string.Empty;

        var builder = new StringBuilder();
        var accessibleEntities = PersistentCraftInventoryHelper.CollectAccessibleEntities(_entityManager, user)
            .OrderBy(entity => entity.Id);

        foreach (var entity in accessibleEntities)
        {
            builder.Append(entity.Id);
            builder.Append(':');
            builder.Append(PersistentCraftInventoryHelper.GetUsableAmount(_entityManager, entity));
            builder.Append(';');
        }

        return builder.ToString();
    }

    private float GetEffectiveCraftTime(PersistentCraftRecipePrototype recipe)
    {
        var reduction = GetUnlockedNodeEffects(recipe)
            .Where(node => node.CraftTimeReductionPercent > 0)
            .Sum(node => node.CraftTimeReductionPercent);

        var multiplier = Math.Max(0.25f, 1f - reduction / 100f);
        return MathF.Max(0.25f, recipe.CraftTime * multiplier);
    }

    private int GetEffectiveIngredientAmount(PersistentCraftRecipePrototype recipe, PersistentCraftIngredient ingredient)
    {
        var reduction = GetUnlockedNodeEffects(recipe)
            .Where(node => node.MaterialCostReductionPercent > 0)
            .Sum(node => node.MaterialCostReductionPercent);

        var multiplier = Math.Max(0.25f, 1f - reduction / 100f);
        return Math.Max(1, (int) MathF.Ceiling(ingredient.Amount * multiplier));
    }

    private IEnumerable<PersistentCraftNodePrototype> GetUnlockedNodeEffects(PersistentCraftRecipePrototype recipe)
    {
        if (_state == null)
            yield break;

        foreach (var nodeId in _state.UnlockedNodes)
        {
            if (!_prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var node))
                continue;

            if (node.Branch != recipe.Branch)
                continue;

            if (PersistentCraftingHelper.GetAffectedTier(node) != recipe.Tier)
                continue;

            yield return node;
        }
    }
}
