using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Message;
using Content.Shared._Stalker.PersistentCrafting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Stalker.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftingWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private static readonly Color WeaponAccent = Color.FromHex("#c77532");
    private static readonly Color ArmorAccent = Color.FromHex("#3d8b86");
    private static readonly Color AnomalyAccent = Color.FromHex("#77923f");
    private static readonly Color PanelBackground = Color.FromHex("#181d25");
    private static readonly Color CardBackground = Color.FromHex("#1e232d");
    private static readonly Color CardUnlockedBackground = Color.FromHex("#1d2823");
    private static readonly Color CardLockedBackground = Color.FromHex("#171a20");
    private static readonly Color CardAvailableBackground = Color.FromHex("#20252d");
    private static readonly Color CardBorder = Color.FromHex("#3b4352");
    private static readonly Color AvailableBorder = Color.FromHex("#647087");
    private static readonly Color UnlockedBorder = Color.FromHex("#8aa06f");
    private static readonly Color SelectedBorder = Color.FromHex("#f1d08a");
    private static readonly Color HeaderTextColor = Color.White;
    private static readonly Color MutedTextColor = Color.FromHex("#aab2c0");
    private static readonly Color DescriptionTextColor = Color.FromHex("#d7dce4");
    private static readonly Color IconBackground = Color.FromHex("#11151b");
    private const float TierTreeNodeWidth = 150f;
    private const float TierTreeNodeHeight = 114f;
    private const float TierTreeHorizontalGap = 28f;
    private const float TierTreeVerticalGap = 24f;
    private const float TierTreePadding = 12f;
    private const float TierTreeLineThickness = 2f;

    private readonly Dictionary<PersistentCraftBranch, string> _selectedTierByBranch = new();
    private readonly Dictionary<PersistentCraftBranch, string> _selectedNodeByBranch = new();
    private bool _selectPreferredBranchOnNextUpdate = true;

    private PersistentCraftState? _state;
    private List<PersistentCraftNodePrototype> _nodes = new();
    private List<PersistentCraftRecipePrototype> _recipes = new();
    private Action<string>? _onUnlock;

    public PersistentCraftingWindow()
    {
        IoCManager.InjectDependencies(this);

        RobustXamlLoader.Load(this);

        Branches.SetTabTitle(0, Loc.GetString("persistent-craft-branch-weapon"));
        Branches.SetTabTitle(1, Loc.GetString("persistent-craft-branch-armor"));
        Branches.SetTabTitle(2, Loc.GetString("persistent-craft-branch-anomaly"));

        PointsLabel.Text = Loc.GetString("persistent-craft-points", ("points", "-"));
        SummaryLabel.SetMarkup(Loc.GetString("persistent-craft-window-summary"));

        Branches.OnTabChanged += _ => RenderBranch(GetCurrentBranch());
    }

    public void UpdateState(
        PersistentCraftState state,
        IEnumerable<PersistentCraftNodePrototype> nodes,
        IEnumerable<PersistentCraftRecipePrototype> recipes,
        Action<string> onUnlock)
    {
        _state = state;
        _nodes = nodes
            .OrderBy(node => node.Branch)
            .ThenBy(node => node.Tier)
            .ThenBy(node => node.SubTier)
            .ThenBy(node => node.ID)
            .ToList();
        _recipes = recipes
            .OrderBy(recipe => recipe.Branch)
            .ThenBy(recipe => recipe.Tier)
            .ThenBy(recipe => recipe.SubTier)
            .ThenBy(recipe => recipe.ID)
            .ToList();
        _onUnlock = onUnlock;

        if (state.Loaded && _selectPreferredBranchOnNextUpdate)
        {
            SelectPreferredBranchTab();
            _selectPreferredBranchOnNextUpdate = false;
        }

        Render();
    }

    public void ResetInitialTabSelection()
    {
        _selectPreferredBranchOnNextUpdate = true;
    }

    private void Render()
    {
        if (_state == null)
            return;

        RenderHeader(_state);
        RenderBranch(GetCurrentBranch());
    }

    private void RenderHeader(PersistentCraftState state)
    {
        if (!state.Loaded)
        {
            PointsLabel.Text = Loc.GetString("persistent-craft-window-loading-points");
            SummaryLabel.SetMarkup(Loc.GetString("persistent-craft-window-loading"));
            return;
        }

        PointsLabel.Text = Loc.GetString("persistent-craft-points", ("points", BuildPointsSummary(state)));
        SummaryLabel.SetMarkup(BuildSummaryMarkup(state));
    }

    private void RenderBranch(PersistentCraftBranch branch)
    {
        var (tierHost, subNodeHost, detailHost) = GetBranchHosts(branch);
        tierHost.RemoveAllChildren();
        subNodeHost.RemoveAllChildren();
        detailHost.RemoveAllChildren();

        if (_state == null)
            return;

        var branchNodes = _nodes.Where(node => node.Branch == branch).ToList();
        var mainTiers = branchNodes
            .Where(PersistentCraftingHelper.IsMainTierNode)
            .OrderBy(node => node.Tier)
            .ToList();

        if (mainTiers.Count == 0)
            return;

        var branchState = GetBranchState(_state, branch);
        var selectedTier = ResolveSelectedTier(branch, mainTiers);
        var subNodes = branchNodes
            .Where(node => !PersistentCraftingHelper.IsMainTierNode(node) && node.Tier == selectedTier.Tier)
            .OrderBy(node => node.SubTier)
            .ToList();
        var selectedNode = ResolveSelectedNode(branch, selectedTier, subNodes);

        tierHost.AddChild(CreateBranchSummary(branch, branchState));
        tierHost.AddChild(new Control { MinSize = new Vector2(1, 10) });
        tierHost.AddChild(CreateSectionHeader(Loc.GetString("persistent-craft-main-tier-label")));
        tierHost.AddChild(new Control { MinSize = new Vector2(1, 8) });
        tierHost.AddChild(CreateMainTierList(branch, mainTiers, selectedTier));

        subNodeHost.AddChild(CreateSectionHeader(Loc.GetString("persistent-craft-subnodes-label")));
        subNodeHost.AddChild(new Control { MinSize = new Vector2(1, 8) });
        if (subNodes.Count == 0)
        {
            subNodeHost.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-none"),
                FontColorOverride = MutedTextColor,
            });
        }
        else
        {
            subNodeHost.AddChild(CreateSubNodeTree(branch, subNodes, selectedNode));
        }

        detailHost.AddChild(CreateDetailsPanel(branchState, selectedNode, subNodes));
    }

    private string BuildPointsSummary(PersistentCraftState state)
    {
        return string.Join(" | ", PersistentCraftingHelper.EnumerateBranches().Select(branch =>
        {
            var branchState = GetBranchState(state, branch);
            return $"{Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(branch))}: {branchState.AvailablePoints}";
        }));
    }

    private string BuildSummaryMarkup(PersistentCraftState state)
    {
        var lines = PersistentCraftingHelper.EnumerateBranches().Select(branch =>
        {
            var branchState = GetBranchState(state, branch);
            return $"[color={MutedTextColor.ToHex()}]{Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(branch))}: " +
                   $"{PersistentCraftingHelper.FormatLevel(branchState.Level, branchState.SubLevel)} | " +
                   $"{Loc.GetString("persistent-craft-experience-label")}: {branchState.Experience}/{branchState.ExperienceForNextLevel} | " +
                   $"{Loc.GetString("persistent-craft-points-short")}: {branchState.AvailablePoints}[/color]";
        }).ToList();

        lines.Add($"[color={MutedTextColor.ToHex()}]{Loc.GetString("persistent-craft-unlocked-summary", ("unlocked", state.UnlockedNodes.Count))}[/color]");
        return string.Join("\n", lines);
    }

    private PanelContainer CreateBranchSummary(PersistentCraftBranch branch, PersistentCraftBranchState branchState)
    {
        var accent = GetBranchAccent(branch);
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CardBackground,
                BorderColor = accent,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8,
            }
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        body.AddChild(new Label
        {
            Text = Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(branch)),
            FontColorOverride = accent,
        });
        body.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-level-label")}: {PersistentCraftingHelper.FormatLevel(branchState.Level, branchState.SubLevel)}",
            FontColorOverride = HeaderTextColor,
        });

        var xpProgress = branchState.ExperienceForNextLevel > 0
            ? Math.Clamp((float)branchState.Experience / branchState.ExperienceForNextLevel, 0f, 1f)
            : 0f;
        body.AddChild(new ProgressBar
        {
            MinSize = new Vector2(0, 6),
            HorizontalExpand = true,
            Value = xpProgress,
        });
        body.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-experience-label")}: {branchState.Experience} / {branchState.ExperienceForNextLevel}",
            FontColorOverride = MutedTextColor,
        });

        body.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-branch-points-label")}: {branchState.AvailablePoints}",
            FontColorOverride = HeaderTextColor,
        });

        panel.AddChild(body);
        return panel;
    }

    private static Label CreateSectionHeader(string text)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = HeaderTextColor,
        };
    }

    private BoxContainer CreateMainTierList(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftNodePrototype> tierNodes,
        PersistentCraftNodePrototype selectedTier)
    {
        var list = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        foreach (var node in tierNodes)
        {
            list.AddChild(CreateMainTierEntry(branch, node, selectedTier.ID == node.ID));
        }

        return list;
    }

    private ContainerButton CreateMainTierEntry(PersistentCraftBranch branch, PersistentCraftNodePrototype node, bool selected)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");
        var branchState = GetBranchState(state, branch);
        var unlocked = HasNodeUnlockedOrAutoAvailable(node.ID);
        var branchLevelMet = branchState.Level >= PersistentCraftingHelper.GetNodeRequiredBranchLevel(node);
        var accent = GetBranchAccent(branch);

        var button = new ContainerButton
        {
            HorizontalExpand = true,
            MinSize = new Vector2(0, 76),
            Margin = new Thickness(0, 0, 0, 8),
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = unlocked ? CardUnlockedBackground : branchLevelMet ? CardAvailableBackground : CardLockedBackground,
                BorderColor = selected ? SelectedBorder : unlocked ? UnlockedBorder : branchLevelMet ? accent : CardBorder,
                BorderThickness = new Thickness(selected ? 2 : 1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 10,
                ContentMarginBottomOverride = 10,
            }
        };
        button.OnPressed += _ => SelectTier(branch, node.ID);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        row.AddChild(CreateNodeIcon(node, selected ? SelectedBorder : accent, new Vector2(52, 52)));
        row.AddChild(new Control { MinSize = new Vector2(10, 1) });

        var textColumn = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        textColumn.AddChild(new Label
        {
            Text = $"{ResolveNodeName(node)} [{PersistentCraftingHelper.GetNodeLevelText(node)}]",
            FontColorOverride = HeaderTextColor,
        });
        textColumn.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-level-label")}: {PersistentCraftingHelper.GetNodeRequiredBranchLevel(node)} | {Loc.GetString(GetMainTierStatusKey(unlocked, branchLevelMet))}",
            FontColorOverride = unlocked ? UnlockedBorder : branchLevelMet ? accent : MutedTextColor,
        });

        row.AddChild(textColumn);
        button.AddChild(row);
        return button;
    }

    private BoxContainer CreateSubNodeTree(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes,
        PersistentCraftNodePrototype selectedNode)
    {
        var accent = GetBranchAccent(branch);
        var positions = subNodes.ToDictionary(node => node.ID, GetNodeTreePosition);
        var maxColumn = positions.Values.Max(position => position.X);
        var maxRow = positions.Values.Max(position => position.Y);

        var layout = new LayoutContainer
        {
            MinSize = new Vector2(
                TierTreePadding * 2 + (maxColumn + 1) * TierTreeNodeWidth + maxColumn * TierTreeHorizontalGap,
                TierTreePadding * 2 + (maxRow + 1) * TierTreeNodeHeight + maxRow * TierTreeVerticalGap + 20),
            HorizontalAlignment = HAlignment.Center,
        };

        foreach (var node in subNodes)
        {
            var childPosition = GetNodeCanvasPosition(positions[node.ID]);
            var childCenter = GetNodeCenter(childPosition);

            var visualParents = GetVisualPrerequisiteIds(node, subNodes).ToList();
            foreach (var prerequisiteId in visualParents)
            {
                if (!positions.TryGetValue(prerequisiteId, out var parentGridPosition))
                    continue;

                var parentPosition = GetNodeCanvasPosition(parentGridPosition);
                var parentCenter = GetNodeCenter(parentPosition);
                AddConnector(layout, parentCenter, childCenter, accent);
            }

        }

        foreach (var node in subNodes)
        {
            var control = CreateSubNodeEntry(branch, node, selectedNode.ID == node.ID);
            control.MinSize = new Vector2(TierTreeNodeWidth, TierTreeNodeHeight);
            LayoutContainer.SetPosition(control, GetNodeCanvasPosition(positions[node.ID]));
            layout.AddChild(control);
        }

        var wrapper = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        };
        wrapper.AddChild(layout);
        return wrapper;
    }

    private Vector2i GetNodeTreePosition(PersistentCraftNodePrototype node)
    {
        if (node.TreeColumn >= 0 && node.TreeRow >= 0)
            return new Vector2i(node.TreeColumn, node.TreeRow);

        return node.SubTier switch
        {
            1 => new Vector2i(1, 0),
            2 => new Vector2i(0, 1),
            3 => new Vector2i(2, 1),
            4 => new Vector2i(1, 2),
            5 => new Vector2i(0, 2),
            6 => new Vector2i(2, 2),
            7 => new Vector2i(1, 3),
            _ => new Vector2i((node.SubTier - 1) % 3, 1 + (node.SubTier - 1) / 3),
        };
    }

    private static IEnumerable<string> GetVisualPrerequisiteIds(
        PersistentCraftNodePrototype node,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes)
    {
        var subNodeIds = subNodes.Select(item => item.ID).ToHashSet();
        var explicitParents = node.Prerequisites.Where(subNodeIds.Contains).ToList();
        if (explicitParents.Count > 0)
            return explicitParents;

        string? TierNode(int subTier) => subNodes.FirstOrDefault(item => item.SubTier == subTier)?.ID;
        var visualParents = new List<string>();

        void AddParent(int subTier)
        {
            var parentId = TierNode(subTier);
            if (!string.IsNullOrWhiteSpace(parentId))
                visualParents.Add(parentId);
        }

        switch (node.SubTier)
        {
            case 2:
            case 3:
                AddParent(1);
                break;
            case 4:
                AddParent(2);
                AddParent(3);
                break;
            case 5:
                AddParent(2);
                AddParent(4);
                break;
            case 6:
                AddParent(3);
                AddParent(4);
                break;
            case 7:
                AddParent(5);
                AddParent(6);
                break;
        }

        return visualParents;
    }

    private static Vector2 GetNodeCanvasPosition(Vector2i gridPosition)
    {
        return new Vector2(
            TierTreePadding + gridPosition.X * (TierTreeNodeWidth + TierTreeHorizontalGap),
            TierTreePadding + gridPosition.Y * (TierTreeNodeHeight + TierTreeVerticalGap));
    }

    private static Vector2 GetNodeCenter(Vector2 canvasPosition)
    {
        return new Vector2(
            canvasPosition.X + TierTreeNodeWidth / 2f,
            canvasPosition.Y + TierTreeNodeHeight / 2f);
    }

    private static void AddConnector(LayoutContainer layout, Vector2 parentCenter, Vector2 childCenter, Color accent)
    {
        var connectorColor = accent.WithAlpha(0.65f);
        var parentBottom = parentCenter.Y + TierTreeNodeHeight / 2f;
        var childTop = childCenter.Y - TierTreeNodeHeight / 2f;
        var midY = parentBottom + (childTop - parentBottom) / 2f;

        AddLine(layout, parentCenter.X, parentBottom, parentCenter.X, midY, connectorColor);
        AddLine(layout, Math.Min(parentCenter.X, childCenter.X), midY, Math.Max(parentCenter.X, childCenter.X), midY, connectorColor);
        AddLine(layout, childCenter.X, midY, childCenter.X, childTop, connectorColor);
    }

    private static void AddLine(LayoutContainer layout, float startX, float startY, float endX, float endY, Color color)
    {
        var isVertical = Math.Abs(startX - endX) < 0.01f;
        var minX = isVertical
            ? startX - TierTreeLineThickness / 2f
            : Math.Min(startX, endX);
        var minY = isVertical
            ? Math.Min(startY, endY)
            : startY - TierTreeLineThickness / 2f;
        var width = isVertical
            ? TierTreeLineThickness
            : Math.Max(Math.Abs(endX - startX), TierTreeLineThickness);
        var height = isVertical
            ? Math.Max(Math.Abs(endY - startY), TierTreeLineThickness)
            : TierTreeLineThickness;

        var line = new PanelContainer
        {
            MinSize = new Vector2(width, height),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color,
            }
        };

        LayoutContainer.SetPosition(line, new Vector2(minX, minY));
        layout.AddChild(line);
    }

    private ContainerButton CreateSubNodeEntry(PersistentCraftBranch branch, PersistentCraftNodePrototype node, bool selected)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");
        var branchState = GetBranchState(state, branch);
        var nodeState = GetNodeState(state, node);
        var unlocked = HasNodeUnlockedOrAutoAvailable(node.ID);
        var prerequisitesMet = node.Prerequisites.All(HasNodeUnlockedOrAutoAvailable);
        var branchLevelMet = branchState.Level >= PersistentCraftingHelper.GetNodeRequiredBranchLevel(node);
        var canUnlock = state.Loaded && !unlocked && prerequisitesMet && branchLevelMet && branchState.AvailablePoints >= node.Cost;
        var accent = GetBranchAccent(branch);

        var button = new ContainerButton
        {
            MinSize = new Vector2(0, 130),
            HorizontalExpand = true,
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = unlocked ? CardUnlockedBackground : canUnlock ? CardAvailableBackground : CardLockedBackground,
                BorderColor = selected ? SelectedBorder : unlocked ? UnlockedBorder : canUnlock ? accent : CardBorder,
                BorderThickness = new Thickness(selected ? 2 : 1),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8,
            }
        };
        button.OnPressed += _ => SelectNode(branch, node.ID);

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        body.AddChild(CreateNodeIcon(node, selected ? SelectedBorder : accent, new Vector2(64, 64)));
        body.AddChild(new Control { MinSize = new Vector2(1, 6) });
        body.AddChild(new Label
        {
            Text = PersistentCraftingHelper.GetNodeLevelText(node),
            FontColorOverride = accent,
            HorizontalAlignment = HAlignment.Center,
        });
        body.AddChild(new Label
        {
            Text = ResolveNodeName(node),
            FontColorOverride = HeaderTextColor,
            HorizontalAlignment = HAlignment.Center,
            ClipText = true,
        });
        if (unlocked)
        {
            body.AddChild(new Control { MinSize = new Vector2(1, 4) });
            body.AddChild(new ProgressBar
            {
                MinSize = new Vector2(0, 5),
                HorizontalExpand = true,
                Value = GetNodeMasteryProgress(node, nodeState),
            });
            body.AddChild(new Label
            {
                Text = BuildNodeMasteryCompactText(node, nodeState),
                FontColorOverride = MutedTextColor,
                HorizontalAlignment = HAlignment.Center,
            });
        }
        else
        {
            body.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-node-cost", ("cost", node.Cost)),
                FontColorOverride = MutedTextColor,
                HorizontalAlignment = HAlignment.Center,
            });
        }

        button.AddChild(body);
        return button;
    }

    private PanelContainer CreateDetailsPanel(
        PersistentCraftBranchState branchState,
        PersistentCraftNodePrototype node,
        IReadOnlyList<PersistentCraftNodePrototype> tierSubNodes)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");
        var nodeState = GetNodeState(state, node);
        var unlocked = HasNodeUnlockedOrAutoAvailable(node.ID);
        var prerequisitesMet = node.Prerequisites.All(HasNodeUnlockedOrAutoAvailable);
        var branchLevelMet = branchState.Level >= PersistentCraftingHelper.GetNodeRequiredBranchLevel(node);
        var canUnlock = state.Loaded &&
                        !PersistentCraftingHelper.IsMainTierNode(node) &&
                        !unlocked &&
                        prerequisitesMet &&
                        branchLevelMet &&
                        branchState.AvailablePoints >= node.Cost;
        var accent = GetBranchAccent(node.Branch);

        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PanelBackground,
                BorderColor = accent,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 14,
                ContentMarginRightOverride = 14,
                ContentMarginTopOverride = 14,
                ContentMarginBottomOverride = 14,
            }
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        body.AddChild(new Label
        {
            Text = $"{ResolveNodeName(node)} [{PersistentCraftingHelper.GetNodeLevelText(node)}]",
            FontColorOverride = HeaderTextColor,
        });
        body.AddChild(new Control { MinSize = new Vector2(1, 8) });
        body.AddChild(CreateNodeIcon(node, accent, new Vector2(120, 120)));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });

        var meta = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        meta.SetMarkup(
            $"[color={MutedTextColor.ToHex()}]{Loc.GetString("persistent-craft-selected-branch", ("branch", Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(node.Branch))))}\n" +
            $"{Loc.GetString("persistent-craft-level-label")}: {PersistentCraftingHelper.FormatLevel(branchState.Level, branchState.SubLevel)} | " +
            $"{Loc.GetString("persistent-craft-branch-points-label")}: {branchState.AvailablePoints}\n" +
            $"{Loc.GetString("persistent-craft-node-cost", ("cost", node.Cost))} | " +
            $"{Loc.GetString(GetDetailStatusKey(node, unlocked, branchLevelMet, prerequisitesMet, canUnlock))}[/color]");
        body.AddChild(meta);
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });

        var description = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        description.SetMarkup($"[color={DescriptionTextColor.ToHex()}]{FormattedMessage.EscapeText(ResolveNodeDescription(node))}[/color]");
        body.AddChild(description);
        body.AddChild(new Control { MinSize = new Vector2(1, 12) });

        body.AddChild(CreateDetailSection(
            Loc.GetString("persistent-craft-node-mastery-label"),
            BuildNodeMasteryMarkup(node, nodeState, unlocked)));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });
        body.AddChild(CreateDetailSection(
            Loc.GetString("persistent-craft-rewards-label"),
            BuildRewardMarkup(node, nodeState, tierSubNodes)));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });
        body.AddChild(CreateDetailSection(
            Loc.GetString("persistent-craft-requirements-label"),
            BuildRequirementMarkup(node)));
        body.AddChild(new Control { VerticalExpand = true });

        var canAttemptUnlock = state.Loaded &&
                               !PersistentCraftingHelper.IsMainTierNode(node) &&
                               !unlocked;

        var unlockButton = new Button
        {
            Text = GetActionText(node, unlocked, canUnlock),
            Disabled = !canAttemptUnlock,
            MinSize = new Vector2(0, 42),
            HorizontalExpand = true,
        };
        unlockButton.OnPressed += _ => _onUnlock?.Invoke(node.ID);

        body.AddChild(unlockButton);
        panel.AddChild(body);
        return panel;
    }

    private PanelContainer CreateDetailSection(string title, string contentMarkup)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CardBackground,
                BorderColor = CardBorder,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8,
            }
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        body.AddChild(new Label
        {
            Text = title,
            FontColorOverride = HeaderTextColor,
        });
        body.AddChild(new Control { MinSize = new Vector2(1, 6) });

        var content = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        content.SetMarkup(contentMarkup);
        body.AddChild(content);

        panel.AddChild(body);
        return panel;
    }

    private PanelContainer CreateNodeIcon(PersistentCraftNodePrototype node, Color accent, Vector2 size)
    {
        var panel = new PanelContainer
        {
            MinSize = size,
            HorizontalAlignment = HAlignment.Center,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = IconBackground,
                BorderColor = accent,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
            }
        };

        if (TryGetNodeTexture(node, out var texture))
        {
            panel.AddChild(new TextureRect
            {
                Texture = texture,
                TextureScale = size.X >= 100 ? new Vector2(2.1f, 2.1f) : new Vector2(1.25f, 1.25f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            });
        }
        else
        {
            panel.AddChild(new Label
            {
                Text = PersistentCraftingHelper.GetNodeLevelText(node),
                FontColorOverride = HeaderTextColor,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            });
        }

        return panel;
    }

    private string BuildRewardMarkup(
        PersistentCraftNodePrototype node,
        PersistentCraftNodeState? nodeState,
        IReadOnlyList<PersistentCraftNodePrototype> tierSubNodes)
    {
        var lines = new List<string>();

        if (PersistentCraftingHelper.IsMainTierNode(node))
        {
            lines.Add($"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-effect-main-tier", ("tier", node.Tier))}[/color]");

            foreach (var subNode in tierSubNodes.OrderBy(item => item.SubTier))
            {
                lines.Add($"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(ResolveNodeName(subNode))} ({PersistentCraftingHelper.GetNodeLevelText(subNode)})[/color]");
            }

            return string.Join("\n", lines);
        }

        if (node.NodeType == PersistentCraftNodeType.RecipeUnlock)
        {
            var recipes = FindRecipesForNode(node).ToList();
            if (recipes.Count == 0)
                return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-none")}[/color]";

            return string.Join("\n", recipes.Select(recipe =>
                $"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(ResolveRecipeName(recipe))} ({PersistentCraftingHelper.GetRecipeLevelText(recipe)})[/color]"));
        }

        if (node.NodeType == PersistentCraftNodeType.MaterialEfficiency)
        {
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-effect-materials", ("tier", PersistentCraftingHelper.GetAffectedTier(node)), ("percent", GetCurrentNodeEffectValue(node, nodeState, node.MaterialCostReductionPercent)))}[/color]";
        }

        if (node.NodeType == PersistentCraftNodeType.CraftSpeed)
        {
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-effect-speed", ("tier", PersistentCraftingHelper.GetAffectedTier(node)), ("percent", GetCurrentNodeEffectValue(node, nodeState, node.CraftTimeReductionPercent)))}[/color]";
        }

        return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-none")}[/color]";
    }

    private string BuildRequirementMarkup(PersistentCraftNodePrototype node)
    {
        var lines = new List<string>();

        if (PersistentCraftingHelper.GetNodeRequiredBranchLevel(node) > 1)
        {
            lines.Add($"[color={DescriptionTextColor.ToHex()}]- {Loc.GetString("persistent-craft-level-label")}: {PersistentCraftingHelper.GetNodeRequiredBranchLevel(node)}[/color]");
        }

        foreach (var prerequisiteId in node.Prerequisites)
        {
            var prerequisite = _nodes.FirstOrDefault(item => item.ID == prerequisiteId);
            if (prerequisite == null)
            {
                lines.Add($"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(prerequisiteId)}[/color]");
                continue;
            }

            lines.Add($"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(ResolveNodeName(prerequisite))} ({PersistentCraftingHelper.GetNodeLevelText(prerequisite)})[/color]");
        }

        if (lines.Count == 0)
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-none")}[/color]";

        return string.Join("\n", lines);
    }

    private string BuildNodeMasteryMarkup(
        PersistentCraftNodePrototype node,
        PersistentCraftNodeState? nodeState,
        bool unlocked)
    {
        if (!unlocked)
        {
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-mastery-locked")}[/color]";
        }

        var state = nodeState ?? CreateDefaultNodeState(node);
        var level = Math.Clamp(state.MasteryLevel, PersistentCraftingHelper.InitialNodeMasteryLevel, PersistentCraftingHelper.MaxNodeMasteryLevel);
        var next = state.ExperienceForNextLevel;

        if (next <= 0 || level >= PersistentCraftingHelper.MaxNodeMasteryLevel)
        {
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-mastery-max", ("level", level), ("max", PersistentCraftingHelper.MaxNodeMasteryLevel))}[/color]";
        }

        return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-mastery-progress", ("level", level), ("max", PersistentCraftingHelper.MaxNodeMasteryLevel), ("experience", state.Experience), ("next", next))}[/color]";
    }

    private PersistentCraftNodePrototype ResolveSelectedTier(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftNodePrototype> tierNodes)
    {
        if (_selectedTierByBranch.TryGetValue(branch, out var selectedId))
        {
            var existing = tierNodes.FirstOrDefault(node => node.ID == selectedId);
            if (existing != null)
                return existing;
        }

        var fallback = tierNodes
                           .Where(node => HasNodeUnlockedOrAutoAvailable(node.ID))
                           .OrderByDescending(node => node.Tier)
                           .FirstOrDefault()
                       ?? tierNodes[0];

        _selectedTierByBranch[branch] = fallback.ID;
        return fallback;
    }

    private PersistentCraftNodePrototype ResolveSelectedNode(
        PersistentCraftBranch branch,
        PersistentCraftNodePrototype selectedTier,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        if (_selectedNodeByBranch.TryGetValue(branch, out var selectedId))
        {
            var existing = subNodes.FirstOrDefault(node => node.ID == selectedId) ??
                           (selectedTier.ID == selectedId ? selectedTier : null);
            if (existing != null)
                return existing;
        }

        var branchState = GetBranchState(state, branch);
        var fallback = subNodes
                           .Where(node => !state.UnlockedNodes.Contains(node.ID) &&
                                          node.Prerequisites.All(HasNodeUnlockedOrAutoAvailable) &&
                                          branchState.Level >= PersistentCraftingHelper.GetNodeRequiredBranchLevel(node) &&
                                          branchState.AvailablePoints >= node.Cost)
                           .OrderBy(node => node.SubTier)
                           .FirstOrDefault()
                       ?? subNodes
                           .Where(node => HasNodeUnlockedOrAutoAvailable(node.ID))
                           .OrderByDescending(node => node.SubTier)
                           .FirstOrDefault()
                       ?? subNodes.FirstOrDefault()
                       ?? selectedTier;

        _selectedNodeByBranch[branch] = fallback.ID;
        return fallback;
    }

    private void SelectTier(PersistentCraftBranch branch, string nodeId)
    {
        _selectedTierByBranch[branch] = nodeId;

        var tierNode = _nodes.FirstOrDefault(item => item.ID == nodeId);
        if (tierNode == null)
        {
            _selectedNodeByBranch[branch] = nodeId;
            RenderBranch(branch);
            return;
        }

        var subNodes = _nodes
            .Where(item => item.Branch == branch &&
                           !PersistentCraftingHelper.IsMainTierNode(item) &&
                           item.Tier == tierNode.Tier)
            .OrderBy(item => item.SubTier)
            .ToList();

        _selectedNodeByBranch[branch] = ResolveSelectedNode(branch, tierNode, subNodes).ID;
        RenderBranch(branch);
    }

    private void SelectNode(PersistentCraftBranch branch, string nodeId)
    {
        _selectedNodeByBranch[branch] = nodeId;

        var node = _nodes.FirstOrDefault(item => item.ID == nodeId);
        if (node != null)
            _selectedTierByBranch[branch] = PersistentCraftingHelper.BuildMainTierNodeId(node.Branch, node.Tier);

        RenderBranch(branch);
    }

    private IEnumerable<PersistentCraftRecipePrototype> FindRecipesForNode(PersistentCraftNodePrototype node)
    {
        return _recipes.Where(recipe =>
        {
            if (!string.IsNullOrWhiteSpace(recipe.RequiredNode))
                return recipe.RequiredNode == node.ID;

            return recipe.Branch == node.Branch &&
                   recipe.Tier == node.Tier &&
                   recipe.SubTier == node.SubTier;
        });
    }

    private bool TryGetNodeTexture(PersistentCraftNodePrototype node, out Texture? texture)
    {
        texture = null;

        var displayProto = node.DisplayProto;
        if (string.IsNullOrWhiteSpace(displayProto))
        {
            var recipe = FindRecipesForNode(node).FirstOrDefault();
            displayProto = recipe == null ? null : PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        }

        if (string.IsNullOrWhiteSpace(displayProto))
            return false;

        try
        {
            var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
            texture = spriteSystem.GetPrototypeIcon(displayProto).Default;
            return texture != null;
        }
        catch
        {
            texture = null;
            return false;
        }
    }

    private string ResolveRecipeName(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype))
        {
            return prototype.Name;
        }

        return Loc.GetString(recipe.Name);
    }

    private string ResolveNodeName(PersistentCraftNodePrototype node)
    {
        if (!string.IsNullOrWhiteSpace(node.Name))
            return Loc.GetString(node.Name);

        return node.NodeType switch
        {
            PersistentCraftNodeType.MainTier =>
                $"{Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(node.Branch))} {PersistentCraftingHelper.GetTierDisplayLabel(node.Tier)}",
            PersistentCraftNodeType.RecipeUnlock => Loc.GetString("persistent-craft-node-sub-recipe-name"),
            PersistentCraftNodeType.MaterialEfficiency => Loc.GetString("persistent-craft-node-sub-material-name"),
            PersistentCraftNodeType.CraftSpeed => Loc.GetString("persistent-craft-node-sub-speed-name"),
            _ => PersistentCraftingHelper.GetNodeLevelText(node),
        };
    }

    private string ResolveNodeDescription(PersistentCraftNodePrototype node)
    {
        if (!string.IsNullOrWhiteSpace(node.Description))
            return Loc.GetString(node.Description);

        return node.NodeType switch
        {
            PersistentCraftNodeType.MainTier =>
                Loc.GetString("persistent-craft-node-effect-main-tier", ("tier", node.Tier)),
            PersistentCraftNodeType.RecipeUnlock => Loc.GetString("persistent-craft-node-sub-recipe-desc"),
            PersistentCraftNodeType.MaterialEfficiency => Loc.GetString("persistent-craft-node-sub-material-desc"),
            PersistentCraftNodeType.CraftSpeed => Loc.GetString("persistent-craft-node-sub-speed-desc"),
            _ => PersistentCraftingHelper.GetNodeLevelText(node),
        };
    }

    private string GetMainTierStatusKey(bool unlocked, bool branchLevelMet)
    {
        if (_state?.Loaded != true)
            return "persistent-craft-node-status-loading";

        if (unlocked)
            return "persistent-craft-node-status-unlocked";

        return branchLevelMet
            ? "persistent-craft-auto-unlock-label"
            : "persistent-craft-node-status-locked";
    }

    private string GetDetailStatusKey(
        PersistentCraftNodePrototype node,
        bool unlocked,
        bool branchLevelMet,
        bool prerequisitesMet,
        bool canUnlock)
    {
        if (_state?.Loaded != true)
            return "persistent-craft-node-status-loading";

        if (PersistentCraftingHelper.IsMainTierNode(node))
            return GetMainTierStatusKey(unlocked, branchLevelMet);

        if (unlocked)
            return "persistent-craft-node-status-unlocked";

        if (canUnlock)
            return "persistent-craft-node-status-available";

        if (!branchLevelMet || !prerequisitesMet)
            return "persistent-craft-node-status-locked";

        return "persistent-craft-node-status-locked";
    }

    private string GetActionText(PersistentCraftNodePrototype node, bool unlocked, bool canUnlock)
    {
        if (_state?.Loaded != true)
            return Loc.GetString("persistent-craft-node-status-loading");

        if (PersistentCraftingHelper.IsMainTierNode(node))
            return Loc.GetString("persistent-craft-auto-unlock-label");

        if (unlocked)
            return Loc.GetString("persistent-craft-node-status-unlocked");

        return Loc.GetString("persistent-craft-node-action-unlock");
    }

    private void SelectPreferredBranchTab()
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        var preferred = PersistentCraftingHelper.EnumerateBranches()
            .Select(branch => new
            {
                Branch = branch,
                Points = GetBranchState(state, branch).AvailablePoints,
            })
            .OrderByDescending(entry => entry.Points)
            .FirstOrDefault(entry => entry.Points > 0);

        if (preferred != null)
            Branches.CurrentTab = GetBranchTabIndex(preferred.Branch);
    }

    private static int GetBranchTabIndex(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => 0,
            PersistentCraftBranch.Armor => 1,
            PersistentCraftBranch.Anomaly => 2,
            _ => 0,
        };
    }

    private PersistentCraftBranch GetCurrentBranch()
    {
        return Branches.CurrentTab switch
        {
            1 => PersistentCraftBranch.Armor,
            2 => PersistentCraftBranch.Anomaly,
            _ => PersistentCraftBranch.Weapon,
        };
    }

    private bool HasNodeUnlockedOrAutoAvailable(string nodeId)
    {
        if (_state == null)
            return false;

        return HasNodeUnlockedOrAutoAvailable(nodeId, new HashSet<string>());
    }

    private bool HasNodeUnlockedOrAutoAvailable(string nodeId, HashSet<string> path)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        if (state.UnlockedNodes.Contains(nodeId))
            return true;

        if (!_prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var node))
            return false;

        if (node.Cost > 0)
            return false;

        var branchState = GetBranchState(state, node.Branch);
        if (branchState.Level < PersistentCraftingHelper.GetNodeRequiredBranchLevel(node))
            return false;

        if (!path.Add(nodeId))
            return false;

        try
        {
            return node.Prerequisites.All(prerequisite => HasNodeUnlockedOrAutoAvailable(prerequisite, path));
        }
        finally
        {
            path.Remove(nodeId);
        }
    }

    private (BoxContainer tierHost, BoxContainer subNodeHost, BoxContainer detailHost) GetBranchHosts(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => (WeaponTierHost, WeaponSubNodeHost, WeaponDetailHost),
            PersistentCraftBranch.Armor => (ArmorTierHost, ArmorSubNodeHost, ArmorDetailHost),
            PersistentCraftBranch.Anomaly => (AnomalyTierHost, AnomalySubNodeHost, AnomalyDetailHost),
            _ => (WeaponTierHost, WeaponSubNodeHost, WeaponDetailHost),
        };
    }

    private static PersistentCraftBranchState GetBranchState(PersistentCraftState state, PersistentCraftBranch branch)
    {
        return state.BranchStates.FirstOrDefault(item => item.Branch == branch) ??
               new PersistentCraftBranchState(
                   branch,
                   0,
                   0,
                   PersistentCraftingHelper.InitialLevel,
                   PersistentCraftingHelper.MainTierSubLevel,
                   0,
                   PersistentCraftingHelper.GetExperienceForNextLevel(PersistentCraftingHelper.InitialLevel));
    }

    private static PersistentCraftNodeState? GetNodeState(PersistentCraftState state, PersistentCraftNodePrototype node)
    {
        return state.NodeStates.FirstOrDefault(item => item.NodeId == node.ID);
    }

    private static PersistentCraftNodeState CreateDefaultNodeState(PersistentCraftNodePrototype node)
    {
        return new PersistentCraftNodeState(
            node.ID,
            PersistentCraftingHelper.InitialNodeMasteryLevel,
            0,
            PersistentCraftingHelper.GetNodeExperienceForNextLevel(node, PersistentCraftingHelper.InitialNodeMasteryLevel));
    }

    private static float GetNodeMasteryProgress(PersistentCraftNodePrototype node, PersistentCraftNodeState? nodeState)
    {
        var state = nodeState ?? CreateDefaultNodeState(node);
        if (state.ExperienceForNextLevel <= 0)
            return 1f;

        return Math.Clamp(state.Experience / (float) state.ExperienceForNextLevel, 0f, 1f);
    }

    private static string BuildNodeMasteryCompactText(PersistentCraftNodePrototype node, PersistentCraftNodeState? nodeState)
    {
        var state = nodeState ?? CreateDefaultNodeState(node);
        return Loc.GetString(
            "persistent-craft-node-mastery-short",
            ("level", state.MasteryLevel),
            ("max", PersistentCraftingHelper.MaxNodeMasteryLevel));
    }

    private static int GetCurrentNodeEffectValue(
        PersistentCraftNodePrototype node,
        PersistentCraftNodeState? nodeState,
        int baseValue)
    {
        if (baseValue <= 0)
            return 0;

        var state = nodeState ?? CreateDefaultNodeState(node);
        var max = PersistentCraftingHelper.MaxNodeMasteryLevel;
        var normalized = Math.Clamp(
            (state.MasteryLevel - PersistentCraftingHelper.InitialNodeMasteryLevel) /
            (float) Math.Max(1, max - PersistentCraftingHelper.InitialNodeMasteryLevel),
            0f,
            1f);
        var multiplier = 0.5f + normalized * 0.5f;
        return Math.Max(1, (int) MathF.Round(baseValue * multiplier));
    }

    private static Color GetBranchAccent(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => WeaponAccent,
            PersistentCraftBranch.Armor => ArmorAccent,
            PersistentCraftBranch.Anomaly => AnomalyAccent,
            _ => CardBorder,
        };
    }
}
